import { Document, Packer, Paragraph, TextRun } from "docx";
import { saveAs } from "file-saver";

export async function exportToDOC(filename = "BusinessPlan", sections = []) {
  if (!sections || sections.length === 0) {
    alert("Tidak ada data untuk diekspor.");
    return;
  }

  const content = [];

  // Title
  content.push(
    new Paragraph({
      children: [
        new TextRun({
          text: "KAWANJUALAN",
          bold: true,
          size: 32,
        }),
      ],
      alignment: "center",
      spacing: { after: 200 },
    })
  );

  content.push(
    new Paragraph({
      children: [
        new TextRun({
          text: "Business Strategy AI Report",
          italics: true,
          size: 22,
        }),
      ],
      alignment: "center",
      spacing: { after: 300 },
    })
  );

  // Body content
  sections.forEach((text) => {
    content.push(
      new Paragraph({
        children: [
          new TextRun({
            text,
            size: 22,
          }),
        ],
        spacing: { after: 250 },
      })
    );
  });

  // Footer
  content.push(
    new Paragraph({
      children: [
        new TextRun({
          text: `Generated by KawanJualan · ${new Date().toLocaleDateString("id-ID")}`,
          size: 18,
          color: "777777",
        }),
      ],
      alignment: "center",
      spacing: { before: 400 },
    })
  );

  const doc = new Document({
    sections: [{ children: content }],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `${filename}.docx`);
}